### ISSUE TITLE
Warn about data which cannot be parsed according to the inferred or specified type

### ISSUE THREAD

**Issue by bjpop** [supernifty/dovex#10]
It would be nice to know if data cannot be parsed according to the inferred or specified type.

Perhaps dovex can have two modes:
1. Abort if data cannot be parsed correctly, and give error saying what happened.
2. Turn un-parsable data into missing values, and report when this happens.

**Comment by supernifty** [comment]
missing or non-numeric values now get replaced with the mean of that column, and the message states how many values have been inferred
